### ISSUE TITLE
v2: grid por colunas e @media

### ISSUE THREAD

**Issue by rafaellindemann** [rafaellindemann/progHub#54]
Acho que, com o novo layout de cards, pode ser interessante tentar usar grid por colunas, para que os cards fiquem dispostos como notas do keep, não alinhados horizontalmente.

Ótima ideia! O layout estilo **Pinterest/Google Keep** é conhecido como **Masonry Layout (Layout de Alvenaria)**. Nele, os cards são organizados em colunas de altura variável, mantendo a largura consistente. Isso resolve o problema de ter descrições curtas e longas sem precisar forçar todos os cards a terem a mesma altura.  

---

### **1. Usando CSS Grid (`grid-auto-flow: dense`)**
O jeito mais moderno e puro CSS:

```css
.container {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); /* Define colunas responsivas */
    grid-auto-rows: 10px; /* Altura base de cada "linha" da grade */
    gap: 16px;
}

.card {
    background: #101010;
    color: white;
    padding: 16px;
    border-radius: 10px;
    display: flex;
    flex-direction: column;
    grid-row: span auto; /* Ajusta dinamicamente o tamanho */
}
```

**Como funciona?**
- `grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));` → Cria colunas responsivas com pelo menos `250px`, mas expande se houver espaço.
- `grid-auto-rows: 10px;` → Faz com que a altura dos cards seja determinada por "blocos" de 10px.
- `grid-row: span auto;` → Permite que os cards cresçam automaticamente para acomodar o conteúdo.

**✅ Vantagens:**
- 100% CSS, sem necessidade de JavaScript.
- Se adapta bem a telas menores.
- Super rápido de renderizar.

**❌ Limitação:**
- Funciona bem, mas não é um **masonry real**, pois os elementos preenchem os espaços da grade apenas horizontalmente.

---

### **2. Usando Masonry com JavaScript (`column-count`)**
Se quiser um efeito mais próximo do Google Keep, pode usar o `column-count` do CSS:

```css
.container {
    column-count: 3; /* Número de colunas padrão */
    column-gap: 16px;
}

.card {
    background: #101010;
    color: white;
    padding: 16px;
    border-radius: 10px;
    display: inline-block; /* Evita que quebre errado */
    width: 100%;
    margin-bottom: 16px;
}
```

E para torná-lo responsivo, basta ajustar o número de colunas via `media queries`:

```css
@media (max-width: 768px) {
    .container {
        column-count: 2; /* 2 colunas em telas menores */
    }
}

@media (max-width: 480px) {
    .container {
        column-count: 1; /* 1 coluna em telas pequenas */
    }
}
```

**✅ Vantagens:**
- Muito simples e 100% CSS.
- Cards fluem de forma natural, sem buracos na grade.

**❌ Limitação:**
- Ordem dos elementos não é mantida corretamente (pode embaralhar um pouco a sequência dos cards).

---

### **3. Usando a Biblioteca `[Masonry.js](https://masonry.desandro.com/)` (100% real)**
Se quiser um **masonry perfeito**, pode usar a biblioteca [Masonry.js](https://masonry.desandro.com/), que faz a distribuição automática dos elementos:

```html
<div class="container">
    <div class="grid">
        <div class="card">Conteúdo 1</div>
        <div class="card">Conteúdo 2</div>
        <div class="card">Conteúdo 3</div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>
<script>
  var msnry = new Masonry('.grid', {
    itemSelector: '.card',
    columnWidth: 250,
    gutter: 16
  });
</script>
```

**✅ Vantagens:**
- O melhor efeito possível, igual ao Google Keep e Pinterest.
- Mantém a ordem dos elementos corretamente.
- Funciona em qualquer navegador.

**❌ Limitação:**
- Depende de JavaScript.
- Pequeno impacto na performance.

---

## **Conclusão: Qual escolher?**
- **Se quiser algo rápido e 100% CSS:** Use **`column-count`**.
- **Se quiser um Masonry moderno sem JS:** Use **CSS Grid**.
- **Se quiser um Masonry real, perfeito:** Use **Masonry.js**.

Se quiser testar um dos métodos no seu projeto, me avisa que eu te ajudo a ajustar! 🚀
